version: '3.8'
services:
  nginxservice:
    build: 
      context: ./requirements/nginx/
    container_name: nginx_c
    restart: always
    ports: 
      - 443:443
    depends_on:
      - wordpress_app
  mariadbservice:
    build: 
        context: ./requirements/mariadb/
    container_name: mariadb_c
    env_file: 
      - ./.env
    volumes:
      - ./requirements/mariadb/tools/mariadb-database-volume:/var/lib/mysql
      - ./requirements/mariadb/conf:/etc/mysql/conf.d 
  wordpress_app:
    build: 
      context: ./requirements/wordpress/
    container_name: wordpress_c
    volumes:
      - ./requirements/wordpress/tools/wordpress_data:/var/www/html
    env_file: 
      - ./.env
    restart: always
    ports:
      - 5000:5000
    depends_on:
        - mariadbservice
volumes:
  wordpress_data:
  mariadb-database-volume: