version: '3.8'
services:
  nginx:
    build: 
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports: 
      - 443:443
    volumes:
      - ./requirements/wordpress/tools/wordpress_data:/var/www/html/wordpress
    depends_on:
      - wordpress
  mariadb:
    build: 
        context: ./requirements/mariadb/
    container_name: mariadb
    env_file: 
      - ./.env
    restart: always
    ports: 
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
  wordpress:
    build: 
      context: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - ./requirements/wordpress/tools/wordpress_data:/var/www/html/wordpress
    env_file: 
      - ./.env
    restart: always
    ports:
      - 9000:9000
    depends_on:
        - mariadb
volumes:
  wordpress_data:
  mariadb_data: