version: '3.8'
services:
  nginx:
    build: 
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - inception
    restart: always
    ports: 
      - 443:443
    volumes:
      - ./requirements/wordpress/tools/wordpress_data:/var/www/html/wordpress
    depends_on:
      - wordpress
  mariadb:
    build: 
        context: ./requirements/mariadb/
        dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception
    env_file: 
      - ./.env
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
  wordpress:
    build: 
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - inception
    volumes:
      - ./requirements/wordpress/tools/wordpress_data:/var/www/html/wordpress
    env_file: 
      - ./.env
    restart: always
    depends_on:
        - mariadb
volumes:
  wordpress_data:
  mariadb_data:
networks:
  inception:
    driver: bridge